Modify bringup to handle the omniinstaller version of chef-server.

diff --git a/setup/01-bringup-chef.install b/setup/01-bringup-chef.install
--- a/setup/01-bringup-chef.install
+++ b/setup/01-bringup-chef.install
@@ -35,7 +35,27 @@ else
     die "Staged on to unknown OS media!"
 fi
 
-if [[ $OS = redhat || $OS = suse ]]; then
+if [[ $OS = ubuntu || $OS = redhat ]]; then
+    mkdir -p /etc/chef-server
+    cat >/etc/chef-server/chef-server.rb <<EOF
+# chef-server settings.
+erchef["listen"]="0.0.0.0"
+erchef["port"]=4000
+erchef["url"]="http://0.0.0.0:4000"
+erchef["web_ui_client_name"]="chef-webui"
+chef_server_webui['port']=4040
+chef_server_webui['url']="http://0.0.0.0:4040"
+chef_server_webui['listen']="0.0.0.0:4040"
+EOF
+    chef-server-ctl reconfigure && \
+        chef-server-ctl test || {
+    echo "Could not bring up valid chef server!"
+    exit 1
+    mkdir -p /etc/chef
+    ln -s /etc/chef-server/chef-webui.pem /etc/chef/webui.pem
+    ln -s /etc/chef-server/chef-validator.pem /etc/chef/validation.pem
+}
+elif [[ $OS = suse ]]; then
     # Default password in chef webui to password
     sed -i 's/web_ui_admin_default_password ".*"/web_ui_admin_default_password "password"/' \
         /etc/chef/webui.rb
@@ -82,11 +102,10 @@ if [[ $OS = redhat || $OS = suse ]]; then
     if [[ ! $chef_webui_running ]]; then
         echo "WARNING: unable to start chef-server-webui"
     fi
+    perl -i -pe 's{<maxFieldLength>.*</maxFieldLength>}{<maxFieldLength>200000</maxFieldLength>}' /var/lib/chef/solr/conf/solrconfig.xml
+
+    service chef-solr restart
 fi
-
-perl -i -pe 's{<maxFieldLength>.*</maxFieldLength>}{<maxFieldLength>200000</maxFieldLength>}' /var/lib/chef/solr/conf/solrconfig.xml
-
-service chef-solr restart
 
 if [[ ! -e ~/.chef/knife.rb ]]; then
     yes '' | knife configure -i
