Rework bringup-chef logic to avoid a potintially unneeded reconfigure of chef-server.

diff --git a/setup/01-bringup-chef.install b/setup/01-bringup-chef.install
--- a/setup/01-bringup-chef.install
+++ b/setup/01-bringup-chef.install
@@ -36,8 +36,12 @@ else
 fi
 
 if [[ $OS = ubuntu || $OS = redhat ]]; then
+    # Set up initial config
+    chef-server-ctl reconfigure
     mkdir -p /etc/chef-server
-    cat >/etc/chef-server/chef-server.rb <<EOF
+    # Customize to match what the rest of Crowbar expects.
+    if [[ ! -f /etc/chef-server/chef-server.rb ]]; then
+        cat >/etc/chef-server/chef-server.rb <<EOF
 # chef-server settings.
 erchef["listen"]="0.0.0.0"
 erchef["port"]=4000
@@ -47,14 +51,16 @@ chef_server_webui['port']=4040
 chef_server_webui['url']="http://0.0.0.0:4040"
 chef_server_webui['listen']="0.0.0.0:4040"
 EOF
-    chef-server-ctl reconfigure && \
-        chef-server-ctl test || {
-    echo "Could not bring up valid chef server!"
-    exit 1
+        # Reconfigure chef-server to match what we expect.
+        chef-server-ctl reconfigure
+    fi
+    chef-server-ctl test || {
+        echo "Could not bring up valid chef server!"
+        exit 1
+    }
     mkdir -p /etc/chef
     ln -s /etc/chef-server/chef-webui.pem /etc/chef/webui.pem
     ln -s /etc/chef-server/chef-validator.pem /etc/chef/validation.pem
-}
 elif [[ $OS = suse ]]; then
     # Default password in chef webui to password
     sed -i 's/web_ui_admin_default_password ".*"/web_ui_admin_default_password "password"/' \
