conditionalize all the chef services bringup.
It is not needed on Ubuntu or Debian.

diff --git a/setup/01-bringup-chef.install b/setup/01-bringup-chef.install
--- a/setup/01-bringup-chef.install
+++ b/setup/01-bringup-chef.install
@@ -10,83 +10,77 @@ ensure_service_running () {
     fi
 }
 
-# Run a command and log its output.
-log_to() {
-    # $1 = install log to log to
-    # $@ = rest of args
-    local __logname="$1" _ret=0
-    local __log="/var/log/install-$1"
-    local __timestamp="$(date '+%F %T %z')"
-    local log_skip_re='^gem|knife$'
-    shift
-    [[ -e $__log.log ]] || echo "Install run done for version: $VERSION" >> $__log.log
-    [[ -e $__log.err ]] || echo "Install run done for version: $VERSION" >> $__log.err
-    printf "\n%s\n" "$__timestamp: Running $*" | \
-        tee -a "$__log.err" >> "$__log.log"
-    "$@" 2>> "$__log.err" >>"$__log.log" || {
-        _ret=$?
-        if ! [[ $__logname =~ $log_skip_re ]]; then
-            echo "$__timestamp: $* failed."
-            echo "See $__log.log and $__log.err for more information."
-        fi
-    }
-    printf "\n$s\n--------\n"  "$(date '+%F %T %z'): Done $*" | \
-        tee -a "$__log.err" >> "$__log.log"
-    return $_ret
+die() {
+    echo "$(date '+%F %T %z'): $@"
+    exit 1
 }
+
 
 service chef-client stop
 
-# Default password in chef webui to password
-sed -i 's/web_ui_admin_default_password ".*"/web_ui_admin_default_password "password"/' /etc/chef/webui.rb
-
-chkconfig rabbitmq-server on
-ensure_service_running rabbitmq-server '^Node .+ with Pid [0-9]+: running'
-
-if rabbitmqctl list_vhosts | grep -q '^/chef$'; then
-    : /chef vhost already added
+if [[ -f /etc/redhat-release || -f /etc/centos-release ]]; then
+    OS=redhat
+elif [[ -d /etc/apt]]; then
+    OS=ubuntu
+elif [[ -f /etc/SuSE-release ]]; then
+    OS=suse
 else
-    rabbitmqctl add_vhost /chef
+    die "Staged on to unknown OS media!"
 fi
 
-if rabbitmqctl list_users 2>&1 | grep -q '^chef	'; then
-    : chef user already added
-else
-    rabbit_chef_password=$( dd if=/dev/urandom count=1 bs=16 2>/dev/null | base64 | tr -d / )
-    rabbitmqctl add_user chef "$rabbit_chef_password"
-    # Update "amqp_pass" in  /etc/chef/server.rb and solr.rb
-    sed -i 's/amqp_pass ".*"/amqp_pass "'"$rabbit_chef_password"'"/' /etc/chef/{server,solr}.rb
+if [[ $OS = redhat || $OS = suse ]]; then
+    # Default password in chef webui to password
+    sed -i 's/web_ui_admin_default_password ".*"/web_ui_admin_default_password "password"/' \
+        /etc/chef/webui.rb
+    chkconfig rabbitmq-server on
+    if ! rabbitmqctl status > /dev/null 2>&1; then
+	echo "RabbitMQ not running. Starting..."
+	chkconfig rabbitmq-server on
+	ensure_service_running rabbitmq-server || \
+            die "Cannot start rabbitmq-server. Aborting."
+        sleep 5
+    fi
+    rabbitmqctl list_vhosts | grep -q '^/chef' || \
+        rabbitmqctl add_vhost /chef || \
+        die "Could not create default rabbitmq Chef vhost"
+    rabbitmqctl list_users | grep -q chef || {
+        rabbitmqctl add_user chef "$rabbit_chef_password"
+        # Update "amqp_pass" in  /etc/chef/server.rb and solr.rb
+        sed -i 's/amqp_pass ".*"/amqp_pass "'"$rabbit_chef_password"'"/' /etc/chef/{server,solr}.rb
+    } || die "Could not create rabbitmq Chef user"
+    rabbitmqctl list_permissions |grep -q chef || \
+	rabbitmqctl set_permissions -p /chef chef ".*" ".*" ".*" || \
+        die "Could not set proper rabbitmq Chef permissions."
+    echo "Starting CouchDB..."
+    chkconfig couchdb on
+
+    services='solr expander server server-webui'
+    for service in $services; do
+        chkconfig chef-${service} on
+    done
+
+    for service in $services; do
+        ensure_service_running chef-${service}
+    done
+
+    # chef-server-webui won't start if /etc/chef/webui.pem doesn't exist, which
+    # may be the case (chef-server generates it if not present, and if the webui
+    # starts too soon, it won't be there yet).
+    for ((x=1; x<6; x++)); do
+        sleep 10
+        service chef-server-webui status >/dev/null && { chef_webui_running=true; break; }
+        service chef-server-webui start
+    done
+    if [[ ! $chef_webui_running ]]; then
+        echo "WARNING: unable to start chef-server-webui"
+    fi
 fi
 
-rabbitmqctl set_permissions -p /chef chef ".*" ".*" ".*"
-
-chkconfig couchdb on
-ensure_service_running couchdb
-
-# increase chef-solr index field size
 perl -i -pe 's{<maxFieldLength>.*</maxFieldLength>}{<maxFieldLength>200000</maxFieldLength>}' /var/lib/chef/solr/conf/solrconfig.xml
 
-services='solr expander server server-webui'
-for service in $services; do
-    chkconfig chef-${service} on
-done
+service chef-solr restart
 
-for service in $services; do
-    ensure_service_running chef-${service}
-done
-
-# chef-server-webui won't start if /etc/chef/webui.pem doesn't exist, which
-# may be the case (chef-server generates it if not present, and if the webui
-# starts too soon, it won't be there yet).
-for ((x=1; x<6; x++)); do
-    sleep 10
-    service chef-server-webui status >/dev/null && { chef_webui_running=true; break; }
-    service chef-server-webui start
-done
-if [[ ! $chef_webui_running ]]; then
-    echo "WARNING: unable to start chef-server-webui"
-fi
-if ! [ -e ~/.chef/knife.rb ]; then
+if [[ !-e ~/.chef/knife.rb ]]; then
     yes '' | knife configure -i
 fi
 
